from lexico import TypeToken as Type

class First:
    PROG = (Type.PROGRAM, Type.PVIRG)
    DECLS = (Type.VAR, Type.PVIRG)
    C_COMP = (Type.ABRECH, Type.PVIRG)
    LIST_DECLS = (Type.ID, Type.PVIRG)
    DECL_TIPO = (Type.ID, Type.PVIRG)
    D = (Type.ID, Type.PVIRG)
    LIST_ID = (Type.ID, Type.PVIRG)
    TIPO = (Type.INT, Type.REAL, Type.BOOL, Type.CHAR)
    E = (Type.VIRG, Type.PVIRG)
    LISTA_COMANDOS = (Type.ID, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    COMANDOS = (Type.ID, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    G = (Type.ID, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    SE = (Type.IF, Type.PVIRG)
    ENQUANTO = (Type.WHILE, Type.PVIRG)
    LEIA = (Type.READ, Type.PVIRG)
    ESCREVA = (Type.WRITE, Type.PVIRG)
    ATRIBUICAO = (Type.ID, Type.ID)
    EXPR = (Type.ID, Type.ABREPAR, Type.CTE, Type.TRUE, Type.FALSE, Type.OPNEG)
    H = (Type.ELSE, Type.PVIRG)
    LIST_W = (Type.ID, Type.ABREPAR, Type.CADEIA, Type.CTE, Type.TRUE, Type.FALSE, Type.OPNEG)
    ELEM_W = (Type.ID, Type.ABREPAR, Type.CADEIA, Type.CTE, Type.TRUE, Type.FALSE, Type.OPNEG)
    L = (Type.VIRG, Type.PVIRG)
    SIMPLES = (Type.ID, Type.ABREPAR, Type.CTE, Type.TRUE, Type.FALSE, Type.OPNEG)
    P = (Type.OPREL, Type.PVIRG)
    TERMO = (Type.ID, Type.ABREPAR, Type.CTE, Type.TRUE, Type.FALSE, Type.OPNEG)
    R = (Type.PVIRG, Type.VIRG, Type.FECHAPAR, Type.OPREL)
    FAT = (Type.ID, Type.ABREPAR, Type.CTE, Type.TRUE, Type.FALSE, Type.OPNEG)
    S = (Type.OPMUL, Type.PVIRG)