from lexico import TypeToken as Type

class Follow:
    PROG = ()
    DECLS = (Type.ABRECH, Type.PVIRG)
    C_COMP = (Type.ID, Type.FECHACH, Type.IF, Type.ELSE, Type.WHILE, Type.READ, Type.WRITE)
    LIST_DECLS = (Type.ABRECH, Type.PVIRG)
    DECL_TIPO = (Type.ID, Type.ABRECH)
    D = (Type.ABRECH, Type.PVIRG)
    LIST_ID = (Type.DPONTOS, Type.FECHAPAR)
    TIPO = (Type.PVIRG, Type.PVIRG)
    E = (Type.DPONTOS, Type.FECHAPAR)
    LISTA_COMANDOS = (Type.FECHACH, Type.PVIRG)
    COMANDOS = (Type.ID, Type.FECHACH, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    G = (Type.FECHACH, Type.PVIRG)
    SE = (Type.ID, Type.FECHACH, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    ENQUANTO = (Type.ID, Type.FECHACH, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    LEIA = (Type.ID, Type.FECHACH, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    ESCREVA = (Type.ID, Type.FECHACH, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    ATRIBUICAO = (Type.ID, Type.FECHACH, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    EXPR = (Type.PVIRG, Type.VIRG, Type.FECHAPAR)
    H = (Type.ID, Type.FECHACH, Type.IF, Type.WHILE, Type.READ, Type.WRITE)
    LIST_W = (Type.FECHAPAR, Type.PVIRG)
    ELEM_W = (Type.VIRG, Type.FECHAPAR)
    L = (Type.FECHAPAR, Type.PVIRG)
    SIMPLES = (Type.PVIRG, Type.VIRG, Type.FECHAPAR, Type.OPREL)
    P = (Type.PVIRG, Type.VIRG, Type.FECHAPAR)
    TERMO = (Type.PVIRG, Type.VIRG, Type.FECHAPAR, Type.OPREL, Type.OPAD)
    R = (Type.PVIRG, Type.VIRG, Type.FECHAPAR, Type.OPREL)
    FAT = (Type.PVIRG, Type.VIRG, Type.FECHAPAR, Type.OPREL, Type.OPAD, Type.OPMUL)
    S = (Type.PVIRG, Type.VIRG, Type.FECHAPAR, Type.OPREL, Type.OPAD)